excluded:
  - Sources/CQuickJS  # Exclude C source files
  - .build

# Enable rules for clarity
opt_in_rules:
  - explicit_enum_raw_value
  - explicit_init
  - explicit_top_level_acl
  - explicit_type_interface
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Configure specific rules
toggle_bool:
  severity: error
  
# Disable rules that conflict with our preferences  
disabled_rules:
  - line_length  # We'll let formatter handle this
  - function_body_length  # Sometimes longer functions are clearer
  - type_body_length  # Sometimes needed for comprehensive types

# Custom configuration
line_length: 120
function_body_length: 60
type_body_length: 300