name: Upstream Release Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'
    
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Bash script
        run: bash .github/scripts/release-checker.sh
          
